<?php


class SeedingData
{

  public array $posts_seed = [
    ["title" => "VP Accounting", "description" => "Spontaneous abortion, with other specified complications, unspecified", "image" => "http://dummyimage.com/148x100.png/5fa2dd/ffffff"],
    ["title" => "Nurse", "description" => "Injury to other specified blood vessels of head and neck", "image" => "http://dummyimage.com/182x100.png/cc0000/ffffff"],
    ["title" => "Internal Auditor", "description" => "Unspecified personality disorder", "image" => "http://dummyimage.com/245x100.png/cc0000/ffffff"],
    ["title" => "Chief Design Engineer", "description" => "Burn of unspecified degree of two or more digits of hand, including thumb", "image" => "http://dummyimage.com/247x100.png/dddddd/000000"],
    ["title" => "Desktop Support Technician", "description" => "Antimalarials and drugs acting on other blood protozoa causing adverse effects in therapeutic use", "image" => "http://dummyimage.com/142x100.png/5fa2dd/ffffff"],
    ["title" => "Registered Nurse", "description" => "Tuberculosis of other urinary organs, bacteriological or histological examination unknown (at present)", "image" => "http://dummyimage.com/189x100.png/ff4444/ffffff"],
    ["title" => "Research Nurse", "description" => "Pneumonitis due to toxoplasmosis", "image" => "http://dummyimage.com/163x100.png/ff4444/ffffff"],
    ["title" => "Accountant III", "description" => "Acute venous embolism and thrombosis of deep vessels of proximal lower extremity", "image" => "http://dummyimage.com/127x100.png/dddddd/000000"],
    ["title" => "Software Test Engineer III", "description" => "Family history of other chronic respiratory conditions", "image" => "http://dummyimage.com/108x100.png/cc0000/ffffff"],
    ["title" => "Marketing Assistant", "description" => "Pulmonary complications of anesthesia or other sedation in labor and delivery, unspecified as to episode of care or not applicable", "image" => "http://dummyimage.com/143x100.png/cc0000/ffffff"],
    ["title" => "Nuclear Power Engineer", "description" => "Chronic osteomyelitis, hand", "image" => "http://dummyimage.com/137x100.png/cc0000/ffffff"],
    ["title" => "VP Accounting", "description" => "Transient paralysis of limb", "image" => "http://dummyimage.com/114x100.png/cc0000/ffffff"],
    ["title" => "Help Desk Technician", "description" => "Obsessive-compulsive personality disorder", "image" => "http://dummyimage.com/180x100.png/dddddd/000000"],
    ["title" => "Sales Associate", "description" => "Fumes from combustion of polyvinylchloride [pvc] and similar material in conflagration in other and unspecified building or structure", "image" => "http://dummyimage.com/175x100.png/cc0000/ffffff"],
    ["title" => "Senior Financial Analyst", "description" => "Butyrophenone-based tranquilizers causing adverse effects in therapeutic use", "image" => "http://dummyimage.com/147x100.png/dddddd/000000"],
    ["title" => "Social Worker", "description" => "Illegally induced abortion, with unspecified complication, complete", "image" => "http://dummyimage.com/144x100.png/5fa2dd/ffffff"],
    ["title" => "Electrical Engineer", "description" => "Congenital hydrocele", "image" => "http://dummyimage.com/116x100.png/5fa2dd/ffffff"],
    ["title" => "Software Test Engineer IV", "description" => "Corneal opacities, interfering with vision, congenital", "image" => "http://dummyimage.com/162x100.png/cc0000/ffffff"],
    ["title" => "VP Accounting", "description" => "Spontaneous abortion, with other specified complications, complete", "image" => "http://dummyimage.com/185x100.png/5fa2dd/ffffff"],
    ["title" => "Statistician II", "description" => "Vaccination not carried out because of caregiver refusal", "image" => "http://dummyimage.com/116x100.png/5fa2dd/ffffff"],
    ["title" => "Senior Quality Engineer", "description" => "Erythema [first degree] of ankle", "image" => "http://dummyimage.com/236x100.png/5fa2dd/ffffff"],
    ["title" => "Internal Auditor", "description" => "Drug-induced mood disorder", "image" => "http://dummyimage.com/250x100.png/5fa2dd/ffffff"],
    ["title" => "Payment Adjustment Coordinator", "description" => "Closed fracture of lumbar vertebra without mention of spinal cord injury", "image" => "http://dummyimage.com/139x100.png/5fa2dd/ffffff"],
    ["title" => "Data Coordinator", "description" => "Calculus of gallbladder and bile duct with acute cholecystitis, with obstruction", "image" => "http://dummyimage.com/133x100.png/dddddd/000000"],
    ["title" => "Senior Developer", "description" => "Crushing injury of shoulder region", "image" => "http://dummyimage.com/104x100.png/ff4444/ffffff"],
    ["title" => "Structural Analysis Engineer", "description" => "Malignant carcinoid tumor of the jejunum", "image" => "http://dummyimage.com/136x100.png/dddddd/000000"],
    ["title" => "Occupational Therapist", "description" => "Cyst of thyroid", "image" => "http://dummyimage.com/205x100.png/ff4444/ffffff"],
    ["title" => "Systems Administrator IV", "description" => "Diabetes with ketoacidosis, type II or unspecified type, not stated as uncontrolled", "image" => "http://dummyimage.com/122x100.png/cc0000/ffffff"],
    ["title" => "Clinical Specialist", "description" => "Sprain of tarsometatarsal (joint) (ligament) of foot", "image" => "http://dummyimage.com/211x100.png/dddddd/000000"],
    ["title" => "Community Outreach Specialist", "description" => "Adult maltreatment, unspecified", "image" => "http://dummyimage.com/229x100.png/cc0000/ffffff"],
    ["title" => "Database Administrator II", "description" => "Postcoital bleeding", "image" => "http://dummyimage.com/231x100.png/5fa2dd/ffffff"],
    ["title" => "Desktop Support Technician", "description" => "Hepatitis, unspecified", "image" => "http://dummyimage.com/137x100.png/5fa2dd/ffffff"],
    ["title" => "Graphic Designer", "description" => "Disorders of other visual pathways associated with neoplasms", "image" => "http://dummyimage.com/193x100.png/cc0000/ffffff"],
    ["title" => "Operator", "description" => "Malignant carcinoid tumor of hindgut, not otherwise specified", "image" => "http://dummyimage.com/210x100.png/5fa2dd/ffffff"],
    ["title" => "Assistant Professor", "description" => "Motor vehicle traffic accident involving collision with other vehicle injuring other specified person", "image" => "http://dummyimage.com/209x100.png/cc0000/ffffff"],
    ["title" => "Recruiting Manager", "description" => "Cortex (cerebral) laceration without mention of open intracranial wound, with concussion, unspecified", "image" => "http://dummyimage.com/209x100.png/ff4444/ffffff"],
    ["title" => "Structural Analysis Engineer", "description" => "Nonspecific reaction to tuberculin skin test without active tuberculosis", "image" => "http://dummyimage.com/124x100.png/cc0000/ffffff"],
    ["title" => "Food Chemist", "description" => "Cardiovascular disease, unspecified", "image" => "http://dummyimage.com/204x100.png/dddddd/000000"],
    ["title" => "Automation Specialist IV", "description" => "Motor vehicle traffic accident involving re-entrant collision with another motor vehicle injuring rider of animal; occupant of animal-drawn vehicle", "image" => "http://dummyimage.com/244x100.png/cc0000/ffffff"],
    ["title" => "Senior Editor", "description" => "Closed dislocation of midtarsal (joint)", "image" => "http://dummyimage.com/153x100.png/ff4444/ffffff"],
    ["title" => "Senior Financial Analyst", "description" => "Torsion of appendix epididymis", "image" => "http://dummyimage.com/238x100.png/cc0000/ffffff"],
    ["title" => "Office Assistant II", "description" => "Other and unspecified open wound of head without mention of complication", "image" => "http://dummyimage.com/118x100.png/ff4444/ffffff"],
    ["title" => "Technical Writer", "description" => "Mobitz (type) II atrioventricular block", "image" => "http://dummyimage.com/127x100.png/cc0000/ffffff"],
    ["title" => "Staff Scientist", "description" => "Diabetes with hyperosmolarity, type II or unspecified type, uncontrolled", "image" => "http://dummyimage.com/231x100.png/ff4444/ffffff"],
    ["title" => "Business Systems Development Analyst", "description" => "Suspected cervical shortening not found", "image" => "http://dummyimage.com/107x100.png/ff4444/ffffff"],
    ["title" => "VP Accounting", "description" => "Primary central nervous system lymphoma, lymph nodes of axilla and upper limb", "image" => "http://dummyimage.com/215x100.png/dddddd/000000"],
    ["title" => "Director of Sales", "description" => "Arcuate uterus", "image" => "http://dummyimage.com/203x100.png/ff4444/ffffff"],
    ["title" => "Senior Sales Associate", "description" => "Posterior dislocation of tibia, proximal end, open", "image" => "http://dummyimage.com/191x100.png/cc0000/ffffff"],
    ["title" => "Assistant Manager", "description" => "Tuberculous peritonitis, unspecified", "image" => "http://dummyimage.com/211x100.png/dddddd/000000"],
    ["title" => "Marketing Manager", "description" => "Subserous leiomyoma of uterus", "image" => "http://dummyimage.com/182x100.png/ff4444/ffffff"],
    ["title" => "Business Systems Development Analyst", "description" => "Failure of sterile precautions during aspiration of fluid or tissue, puncture, and catheterization", "image" => "http://dummyimage.com/114x100.png/dddddd/000000"],
    ["title" => "Marketing Assistant", "description" => "Accident to watercraft causing other injury to occupant of small boat, unpowered", "image" => "http://dummyimage.com/210x100.png/5fa2dd/ffffff"],
    ["title" => "VP Accounting", "description" => "Open fracture of astragalus", "image" => "http://dummyimage.com/161x100.png/dddddd/000000"],
    ["title" => "Tax Accountant", "description" => "Common ventricle", "image" => "http://dummyimage.com/143x100.png/dddddd/000000"],
    ["title" => "Structural Engineer", "description" => "Arthropathy associated with hematological disorders", "image" => "http://dummyimage.com/192x100.png/dddddd/000000"],
    ["title" => "Director of Sales", "description" => "Benign essential hypertension complicating pregnancy, childbirth, and the puerperium, postpartum condition or complication", "image" => "http://dummyimage.com/124x100.png/ff4444/ffffff"],
    ["title" => "Environmental Specialist", "description" => "Laryngeal diphtheria", "image" => "http://dummyimage.com/202x100.png/5fa2dd/ffffff"],
    ["title" => "Recruiter", "description" => "Other complications due to other vascular device, implant, and graft", "image" => "http://dummyimage.com/109x100.png/5fa2dd/ffffff"],
    ["title" => "Recruiting Manager", "description" => "Other and unspecified intracranial hemorrhage following injury with open intracranial wound, with no loss of consciousness", "image" => "http://dummyimage.com/239x100.png/ff4444/ffffff"],
    ["title" => "Recruiting Manager", "description" => "Human herpesvirus 7 infection", "image" => "http://dummyimage.com/234x100.png/5fa2dd/ffffff"],
    ["title" => "Recruiter", "description" => "Open wound of other and unspecified parts of genital organs (external), without mention of complication", "image" => "http://dummyimage.com/164x100.png/ff4444/ffffff"],
    ["title" => "Assistant Professor", "description" => "Cochlear otosclerosis", "image" => "http://dummyimage.com/197x100.png/5fa2dd/ffffff"],
    ["title" => "Payment Adjustment Coordinator", "description" => "Need for prophylactic vaccination and inoculation against other arthropod-borne viral diseases", "image" => "http://dummyimage.com/214x100.png/cc0000/ffffff"],
    ["title" => "Database Administrator IV", "description" => "Calculus of gallbladder without mention of cholecystitis, with obstruction", "image" => "http://dummyimage.com/158x100.png/dddddd/000000"],
    ["title" => "Mechanical Systems Engineer", "description" => "Open posterior dislocation of hip", "image" => "http://dummyimage.com/113x100.png/ff4444/ffffff"],
    ["title" => "Business Systems Development Analyst", "description" => "Acute pyelonephritis with lesion of renal medullary necrosis", "image" => "http://dummyimage.com/137x100.png/cc0000/ffffff"],
    ["title" => "Web Developer IV", "description" => "Other otorrhea", "image" => "http://dummyimage.com/249x100.png/5fa2dd/ffffff"],
    ["title" => "Senior Cost Accountant", "description" => "Herpes zoster myelitis", "image" => "http://dummyimage.com/194x100.png/5fa2dd/ffffff"],
    ["title" => "Junior Executive", "description" => "Optic atrophy associated with retinal dystrophies", "image" => "http://dummyimage.com/163x100.png/5fa2dd/ffffff"],
    ["title" => "Automation Specialist II", "description" => "Closed fractures involving skull or face with other bones, with cerebral laceration and contusion, with prolonged [more than 24 hours] loss of consciousness, without return to pre-existing conscious level", "image" => "http://dummyimage.com/190x100.png/cc0000/ffffff"],
    ["title" => "Automation Specialist III", "description" => "Carcinoma in situ, unspecified female genital organ", "image" => "http://dummyimage.com/189x100.png/cc0000/ffffff"],
    ["title" => "Recruiting Manager", "description" => "Need for prophylactic vaccination and inoculation against diphtheria-tetanus-pertussis, combined [DTP] [DTaP]", "image" => "http://dummyimage.com/243x100.png/dddddd/000000"],
    ["title" => "VP Accounting", "description" => "Acute pulmonary manifestations due to radiation", "image" => "http://dummyimage.com/180x100.png/dddddd/000000"],
    ["title" => "Safety Technician I", "description" => "Unspecified personality disorder", "image" => "http://dummyimage.com/201x100.png/dddddd/000000"],
    ["title" => "Senior Cost Accountant", "description" => "Acute allergic mucoid otitis media", "image" => "http://dummyimage.com/106x100.png/cc0000/ffffff"],
    ["title" => "Junior Executive", "description" => "Toxic encephalitis and encephalomyelitis", "image" => "http://dummyimage.com/104x100.png/cc0000/ffffff"],
    ["title" => "Registered Nurse", "description" => "Other urinary problems", "image" => "http://dummyimage.com/219x100.png/cc0000/ffffff"],
    ["title" => "Account Representative IV", "description" => "Methicillin susceptible Staphylococcus aureus in conditions classified elsewhere and of unspecified site", "image" => "http://dummyimage.com/124x100.png/ff4444/ffffff"],
    ["title" => "Structural Engineer", "description" => "Spotting complicating pregnancy, antepartum condition or complication", "image" => "http://dummyimage.com/156x100.png/ff4444/ffffff"],
    ["title" => "Human Resources Assistant IV", "description" => "Assault by pushing from a high place", "image" => "http://dummyimage.com/155x100.png/ff4444/ffffff"],
    ["title" => "Speech Pathologist", "description" => "Unspecified polyarthropathy or polyarthritis, upper arm", "image" => "http://dummyimage.com/157x100.png/5fa2dd/ffffff"],
    ["title" => "Environmental Tech", "description" => "Isolated tracheal or bronchial tuberculosis, unspecified", "image" => "http://dummyimage.com/185x100.png/ff4444/ffffff"],
    ["title" => "Social Worker", "description" => "Open fracture of vault of skull with other and unspecified intracranial hemorrhage, with prolonged [more than 24 hours] loss of consciousness, without return to pre-existing conscious level", "image" => "http://dummyimage.com/205x100.png/5fa2dd/ffffff"],
    ["title" => "Professor", "description" => "Infection by Histoplasma capsulatum, other", "image" => "http://dummyimage.com/231x100.png/5fa2dd/ffffff"],
    ["title" => "Senior Quality Engineer", "description" => "Posttraumatic wound infection not elsewhere classified", "image" => "http://dummyimage.com/248x100.png/ff4444/ffffff"],
    ["title" => "Quality Engineer", "description" => "Cutaneous-vesicostomy", "image" => "http://dummyimage.com/159x100.png/5fa2dd/ffffff"],
    ["title" => "Nuclear Power Engineer", "description" => "Suppressed lactation, delivered, with mention of postpartum complication", "image" => "http://dummyimage.com/104x100.png/dddddd/000000"],
    ["title" => "Chief Design Engineer", "description" => "Abnormal jaw closure", "image" => "http://dummyimage.com/162x100.png/ff4444/ffffff"],
    ["title" => "Recruiting Manager", "description" => "Other inflammatory disorders of penis", "image" => "http://dummyimage.com/198x100.png/ff4444/ffffff"],
    ["title" => "Account Representative II", "description" => "Other chronic infective otitis externa", "image" => "http://dummyimage.com/214x100.png/cc0000/ffffff"],
    ["title" => "Junior Executive", "description" => "Other complications of anesthesia or other sedation in labor and delivery, delivered, with or without mention of antepartum condition", "image" => "http://dummyimage.com/177x100.png/dddddd/000000"],
    ["title" => "Financial Analyst", "description" => "Infections of genitourinary tract in pregnancy, postpartum condition or complication", "image" => "http://dummyimage.com/183x100.png/ff4444/ffffff"],
    ["title" => "Statistician II", "description" => "Disorder of organs of special sense arising from mental factors", "image" => "http://dummyimage.com/233x100.png/5fa2dd/ffffff"],
    ["title" => "Mechanical Systems Engineer", "description" => "Injury due to war operations from fire caused indirectly from conventional weapon", "image" => "http://dummyimage.com/146x100.png/5fa2dd/ffffff"],
    ["title" => "Civil Engineer", "description" => "Suicide and self-inflicted poisoning by other specified gases and vapors", "image" => "http://dummyimage.com/141x100.png/cc0000/ffffff"],
    ["title" => "VP Product Management", "description" => "Late effects of motor vehicle accident", "image" => "http://dummyimage.com/123x100.png/dddddd/000000"],
    ["title" => "Marketing Assistant", "description" => "Closed fractures involving skull or face with other bones, with other and unspecified intracranial hemorrhage, with concussion, unspecified", "image" => "http://dummyimage.com/158x100.png/dddddd/000000"],
    ["title" => "Civil Engineer", "description" => "Personal history of malignant neoplasm of ovary", "image" => "http://dummyimage.com/192x100.png/5fa2dd/ffffff"],
    ["title" => "Account Coordinator", "description" => "Rumination disorder", "image" => "http://dummyimage.com/247x100.png/ff4444/ffffff"],
    ["title" => "Senior Editor", "description" => "Open fracture of mandible, alveolar border of body", "image" => "http://dummyimage.com/197x100.png/5fa2dd/ffffff"],];

  public function seeding_data()
  {
    return $this->posts_seed;
  }
}
